//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiErLan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public string Keys { get; set; }
        public string Contents { get; set; }
        public string Title { get; set; }
        public string Remark { get; set; }
        public string Images { get; set; }
        public string Intro { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> ShowTime { get; set; }
    }
}
